apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  USER: root
  # PASSWORD: password_mysql
  DATABASE_URL: mysql://10.60.20.11:3306/SpringWebYoutube?useTimezone=true&serverTimezone=UTC
  # DATABASE_URL: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC # caso esteja vinculando um clusterIP na mão
        