- name: PHASE 02 - Initialize control-plane and cluster
  hosts: masters_primary
  become: true
  vars:
    load_balancer_dns: "{{ lookup('file', 'tmp/k8s_lb_dns_name') }}"
    load_balancer_port: "6443"
  tasks:
    - debug:
        msg: 'kubeadm init --upload-certs --control-plane-endpoint "{{ load_balancer_dns }}:{{ load_balancer_port }}"'

    - name: Kubeadm init
      shell: kubeadm init --upload-certs --control-plane-endpoint "{{ load_balancer_dns }}:{{ load_balancer_port }}"
      register: initResult
      ignore_errors: yes

    - name: "Wait for cluster initialization."
      wait_for:
        timeout: 5

    - name: Store Kubeadm init output
      action: copy content="{{ initResult.stdout }}" dest="/etc/kubernetes/kubeadm-init.stdout"

    - name: Create .kube folder
      file:
        path: "~{{ ansible_ssh_user }}/.kube"
        state: directory
        owner: "{{ ansible_ssh_user }}"

    - name: Copy admin.conf to .kube folder
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "~{{ ansible_ssh_user }}/.kube/config"
        owner: "{{ ansible_ssh_user }}"
        remote_src: yes

    - name: Create .kube folder
      file:
        path: "/root/.kube"
        state: directory
        owner: "root"

    - name: Copy admin.conf to .kube folder
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/root/.kube/config"
        owner: "root"
        remote_src: yes
